### ISSUE TITLE
Remove TOML file from repo and just provide a sample file

### ISSUE THREAD

**Issue by ashfame** [Automattic/neurobot#55] opened 2022-03-21 19:11 UTC

**Comment by psrpinto** [comment] 2022-03-22 12:06
Duplicate of #24 ?

**Comment by ashfame** [comment] 2022-03-22 12:50
I guess, but quite limited in scope than that. Just need to get the TOML file out of repo here to finish this off and then pick it up in #24?

**Closed** 2022-04-08 13:10 UTC
